GENERAL_PAGE = "General"
ABOUT_PAGE = "About"
PRESS_PAGE = "Press"
BLOG_PAGE = "Blog"
CAREERS_PAGE = "Careers"
DEVELOPERS_PAGE = "Developer"
HELP_CENTER_PAGE = "Help Center"
BROWSE_INCOLLEGE_PAGE = "Browse InCollege"
BUSINESS_SOLUTIONS_PAGE = "Business Solutions"
DIRECTORIES_PAGE = "Directories"
COPYRIGHT_NOTICE_PAGE = "Copyright Notice"

START_PAGE = "Start Page"
LOGIN_PAGE = "Login"
SIGN_UP_PAGE = "Sign Up"
PLAY_VIDEO_PAGE = "Play video (\"Why Join InCollege?\")"
SEARCH_FOR_USERS_PAGE = "Search for InCollege users"
USEFUL_LINKS_PAGE = "Useful Links"
IMPORTANT_LINKS_PAGE = "InCollege Important Links"
EXIT_PAGE = "Exit"

TOP_LEVEL_MENU_PAGE = "Top Level Menu"
JOB_SEARCH_PAGE = "Search for an internship/job"
FIND_SOMEONE_YOU_KNOW_PAGE = "Find someone you know"
LEARN_SKILLS_PAGE = "Learn a new skill"