USEFUL_LINKS_PAGE = "Useful Links"
GENERAL_PAGE = "General"
ABOUT_PAGE = "About"
PRESS_PAGE = "Press"
BLOG_PAGE = "Blog"
CAREERS_PAGE = "Careers"
DEVELOPERS_PAGE = "Developer"
HELP_CENTER_PAGE = "Help Center"
BROWSE_INCOLLEGE_PAGE = "Browse InCollege"
BUSINESS_SOLUTIONS_PAGE = "Bussiness Solutions"
DIRECTORIES_PAGE = "Directories"
COPYRIGHT_NOTICE_PAGE = "Copyright Notice"

START_PAGE = "Start Page"
LOGIN_PAGE = "Login"
SIGN_UP_PAGE = "Sign Up"
TOP_LEVEL_MENU_PAGE = "Top Level Menu"