ABOUT_PAGE = "About"
ACCESSIBILITY_PAGE = "Accessibility"
BLOG_PAGE = "Blog"
BRAND_POLICY_PAGE = "Brand Policy"
BROWSE_INCOLLEGE_PAGE = "Browse InCollege"
BUSINESS_SOLUTIONS_PAGE = "Business Solutions"
CAREERS_PAGE = "Careers"
COOKIE_POLICY_PAGE = "Cookie Policy"
COPYRIGHT_NOTICE_PAGE = "Copyright Notice"
COPYRIGHT_POLICY_PAGE = "Copyright Policy"
DEVELOPERS_PAGE = "Developer"
DIRECTORIES_PAGE = "Directories"
FIND_SOMEONE_YOU_KNOW_PAGE = "Find someone you know"
EXIT_PAGE = "Exit"
GENERAL_PAGE = "General"
GUEST_CONTROLS_PAGE = "Guest Controls"
HELP_CENTER_PAGE = "Help Center"
IMPORTANT_LINKS_PAGE = "InCollege Important Links"
JOB_SEARCH_PAGE = "Search for an internship/job"
JOB_POST_PAGE = "Post a job"
LANGUAGES_PAGE = "Language Settings"
LEARN_SKILLS_PAGE = "Learn a new skill"
LOGIN_PAGE = "Login"
PLAY_VIDEO_PAGE = "Play video (\"Why Join InCollege?\")"
PRESS_PAGE = "Press"
PRIVACY_POLICY_PAGE = "Privacy Policy"
SEARCH_FOR_USERS_PAGE = "Search for InCollege users"
SIGN_UP_PAGE = "Sign Up"
START_PAGE = "Start Page"
TOP_LEVEL_MENU_PAGE = "Top Level Menu"
USEFUL_LINKS_PAGE = "Useful Links"
USER_AGREEMENT_PAGE = "User Agreement"




