ABOUT_SCREEN = "About"
ACCESSIBILITY_SCREEN = "Accessibility"
BLOG_SCREEN = "Blog"
BRAND_POLICY_SCREEN = "Brand Policy"
BROWSE_INCOLLEGE_SCREEN = "Browse InCollege"
BUSSINESS_SOLUTIONS_SCREEN = "Bussiness Solutions"
CAREERS_SCREEN = "Careers"
CODING_SCREEN = "Coding"
COMMUNICATION_SCREEN = "Communication"
COOKIE_POLICY_SCREEN = "Cookie Policy"
COPYRIGHT_NOTICE_SCREEN = "Copyright Notice"
COPYRIGHT_POLICY_SCREEN = "Copyright Policy"
CREATE_PROFILE_SCREEN = "Create Profile"
CURRENT_FRIENDS_SCREEN = "Current Friends"
DEVELOPERS_SCREEN = "Developers"
DIRECTORIES_SCREEN = "Directories"
FIND_CONTACT_SCREEN = "Find Contact"
FIND_FRIENDS_SCREEN = "Find Friends"
GENERAL_SCREEN = "General"
GUEST_CONTROLS_SCREEN = "Guest Control"
HELP_CENTER_SCREEN = "Help Center"
INCOLLEGE_IMPORTANT_LINKS_SCREEN = "Important Links"
JOB_SEARCH_SCREEN = "Job Search Screen"
LANGUAGE_SCREEN = "Language"
LEARN_NEW_SKILL_SCREEN = "Learn New Skill"
LOGIN_SCREEN = "Login Screen"
MICROSOFT_EXCEL_SCREEN = "Microsoft Excel"
PENDING_FRIEND_REQUEST_SCREEN = "Pending Requests"
PRESS_SCREEN = "Press"
PREVIOUS_SCREEN = "Previous Screen"
PRIVACY_POLICY_SCREEN = "Privacy Policy"
PROMOTIONAL_VIDEO_SCREEN = "Promotional Video"
RESUME_CRITIQUE_SCREEN = "Resume Critique"
SHOW_MY_NETWORK_SCREEN = "Show My Network"
SIGNUP_SCREEN = "Sign Up Screen"
STARTUP_SCREEN = "Startup Screen"
WEB_DEVELOPMENT_SCREEN = "Web Development"
USER_HOME_SCREEN = "Home Screen"
USEFUL_LINKS_SCREEN = "Useful Links"
USER_AGREEMENT_SCREEN = "User Agreement"


screens = [
    PREVIOUS_SCREEN, STARTUP_SCREEN, LOGIN_SCREEN, SIGNUP_SCREEN,
    JOB_SEARCH_SCREEN, USER_HOME_SCREEN, BROWSE_INCOLLEGE_SCREEN,
    BUSSINESS_SOLUTIONS_SCREEN, DIRECTORIES_SCREEN, USEFUL_LINKS_SCREEN,
    GENERAL_SCREEN, ABOUT_SCREEN, BLOG_SCREEN, CAREERS_SCREEN, DEVELOPERS_SCREEN,
    HELP_CENTER_SCREEN, PRESS_SCREEN, LEARN_NEW_SKILL_SCREEN, CODING_SCREEN,
    COMMUNICATION_SCREEN,CREATE_PROFILE_SCREEN, MICROSOFT_EXCEL_SCREEN, RESUME_CRITIQUE_SCREEN,
    WEB_DEVELOPMENT_SCREEN, INCOLLEGE_IMPORTANT_LINKS_SCREEN,
    ACCESSIBILITY_SCREEN, BRAND_POLICY_SCREEN, COOKIE_POLICY_SCREEN,
    COPYRIGHT_NOTICE_SCREEN, COPYRIGHT_POLICY_SCREEN, GUEST_CONTROLS_SCREEN,
    LANGUAGE_SCREEN, PRIVACY_POLICY_SCREEN, USER_AGREEMENT_SCREEN,
    PROMOTIONAL_VIDEO_SCREEN, FIND_CONTACT_SCREEN, SHOW_MY_NETWORK_SCREEN,
    FIND_FRIENDS_SCREEN, CURRENT_FRIENDS_SCREEN, PENDING_FRIEND_REQUEST_SCREEN
]
